### ISSUE TITLE
AUTH command

### ISSUE THREAD

**Issue by ianpark** [hmartiro/redox#36]
Hi,

I am using Redis with authentication so doing this:
rdx.command<int>({"auth", "mypassword"}, [](Command<int>& c) {
    if(!c.ok()) return;
    cout << "Auth is done." << endl;
  });

And seeing this error message:
(2015-12.10 22:26:02) [Error]  	auth mypassword: Received reply of type 5, expected type 3.

in spite of this error, the next commands are processed fine.

Could you explain what is going on?

Regards,

Ian

**Comment by ianpark** [comment]
sorry it should have been <string> How do I know which reply type is matching to specific command?

**Comment by hmartiro** [comment]
Hello. The command method is templated on the expected reply type, which you should find in the Redis documentation.
