### ISSUE TITLE
Removing logging

### ISSUE THREAD

**Issue by ujvl** [hmartiro/redox#42]
Is there a config file where we can edit the logging level? Or alternatively is there a way to do so programmatically? [This](https://github.com/hmartiro/redox/blob/master/include/redox/utils/logger.hpp) seems like the relevant class.

**Comment by hmartiro** [comment]
You can specify the logging level in the constructor of the Redox object:

`Redox(std::ostream &log_stream = std::cout, log::Level log_level = log::Warning);`

See include/redox/client.hpp for details.
